In [6]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Replace 'username/mentalbert' with the actual model repository path
model_name = "Sharath45/MENTALBERT_MULTILABEL_CLASSIFICATION"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Example: Analyzing mental health related text
text = "I have been feeling very low and anxious recently."
inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)

# Convert logits to probabilities
probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(probabilities)


tokenizer_config.json: 0.00B [00:00, ?B/s]

C:\Users\hana\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hana\.cache\huggingface\hub\models--Sharath45--MENTALBERT_MULTILABEL_CLASSIFICATION. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tensor([[3.1807e-03, 1.4321e-02, 3.0972e-03, 9.7854e-01, 8.6306e-04]],
       grad_fn=<SoftmaxBackward0>)


In [7]:
text= "I [21/M] am unsure if I should tell my friends about my health issues. I am currently doing a couple of research projects at university in the biology building as a post-grad. My lab mates, all of whom are at least 3 years older than me, and I all care about each other as friends; we hang out, joke around, and like to keep a friendly atmosphere. This usually leads to most of them noticing when something is wrong with someone by the look on their face, and this is especially the case with me on some days. I had a blood test done recently which showed that 40% of my hemoglobin is HbS, which is characteristic of Sickle Cell trait and another co-existing condition, which is unknown to me at the moment (I'm working with my doctor to figure it out). Sometimes I show up to the lab in the morning and am just tired all around; it has no effect on my productivity, but I just don't feel like socializing at the moment, and some of my friends get the feeling that I'm trying to brush them off. In reality, I'm just exhausted, physically and mentally.\
What I'm worried about, because of past experiences with acquaintances, is that if I tell them about my chronic issue, it's going to cause a great deal of worry and/or stress over me, and I don't wish that at all, since I'm going to be working in the lab for the next year, and some of my lab mates have to present at conferences in a couple of months. I'm the type of person to work through tiredness and exhaustion if it means I can get some valuable output/results,\
so I'm not worried about myself. Am I analyzing a bit too much, or is this something my adviser and lab mates need to know?\
tl;dr: Chronic blood issue causes fatigue for me almost everyday, and friends and lab mates are worried about me looking tired all the time. Should I tell them, or keep saying that I'm alright?"

inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)

# Convert logits to probabilities
probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(probabilities)

tensor([[0.0035, 0.9222, 0.0092, 0.0612, 0.0040]], grad_fn=<SoftmaxBackward0>)


In [2]:
from huggingface_hub import notebook_login

notebook_login()

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")



In [13]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Replace 'username/mentalbert' with the actual model repository path
model_name = "slimshady07/Mental_BERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Example: Analyzing mental health related text
text = "I have been feeling very low and anxious recently."
inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)

# Convert logits to probabilities
probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(probabilities)


tensor([[0.5299, 0.4701]], grad_fn=<SoftmaxBackward0>)


In [14]:
text= "I [21/M] am unsure if I should tell my friends about my health issues. I am currently doing a couple of research projects at university in the biology building as a post-grad. My lab mates, all of whom are at least 3 years older than me, and I all care about each other as friends; we hang out, joke around, and like to keep a friendly atmosphere. This usually leads to most of them noticing when something is wrong with someone by the look on their face, and this is especially the case with me on some days. I had a blood test done recently which showed that 40% of my hemoglobin is HbS, which is characteristic of Sickle Cell trait and another co-existing condition, which is unknown to me at the moment (I'm working with my doctor to figure it out). Sometimes I show up to the lab in the morning and am just tired all around; it has no effect on my productivity, but I just don't feel like socializing at the moment, and some of my friends get the feeling that I'm trying to brush them off. In reality, I'm just exhausted, physically and mentally.\
What I'm worried about, because of past experiences with acquaintances, is that if I tell them about my chronic issue, it's going to cause a great deal of worry and/or stress over me, and I don't wish that at all, since I'm going to be working in the lab for the next year, and some of my lab mates have to present at conferences in a couple of months. I'm the type of person to work through tiredness and exhaustion if it means I can get some valuable output/results,\
so I'm not worried about myself. Am I analyzing a bit too much, or is this something my adviser and lab mates need to know?\
tl;dr: Chronic blood issue causes fatigue for me almost everyday, and friends and lab mates are worried about me looking tired all the time. Should I tell them, or keep saying that I'm alright?"

inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)

# Convert logits to probabilities
probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(probabilities)

tensor([[0.1779, 0.8221]], grad_fn=<SoftmaxBackward0>)


In [15]:
import pandas as pd
domain_data=pd.read_csv('non_mental_disorders_relevent_subreddits_control.csv')

C:\Users\hana\AppData\Local\Temp\ipykernel_34820\2475463666.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  domain_data=pd.read_csv('non_mental_disorders_relevent_subreddits_control.csv')


In [16]:
model.to(device)
model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [17]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.utils.data import DataLoader
from datasets import Dataset
import numpy as np


In [ ]:
domain_data.sample(frac=1,random_state=42)
domain_to_test=domain_data[:10000]


In [27]:

domain_to_test['label']=1


C:\Users\hana\AppData\Local\Temp\ipykernel_34820\613866498.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  domain_to_test['label']=1


In [57]:
dataset = Dataset.from_pandas(domain_to_test)

def tokenize(batch):
    return tokenizer(
        batch['other_posts'],
        truncation=True,
        padding="max_length",
        max_length=512
    )

dataset = dataset.map(tokenize, batched=True)
dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

test_loader = DataLoader(dataset, batch_size=32, shuffle=False)


Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

In [59]:
print(all_labels.dtype, all_preds.dtype)
print(np.unique(all_labels), np.unique(all_preds))


int64 int64
[1] [0 1]


In [ ]:
from torch.nn.functional import softmax

total_loss = 0
all_preds = []
all_probs = []
all_labels = []

criterion = torch.nn.CrossEntropyLoss()

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        logits = outputs.logits
        loss = criterion(logits, labels)

        probs = softmax(logits, dim=1)
        preds = torch.argmax(probs, dim=1)

        total_loss += loss.item()

        all_preds.extend(preds.cpu().numpy())
        all_probs.extend(probs[:, 1].cpu().numpy())  # prob of mental illness
        all_labels.extend(labels.cpu().numpy())


In [65]:
from sklearn.metrics import classification_report
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

accuracy = (all_preds == all_labels).mean()

false_positives = (all_preds == 1).sum()
false_positive_rate = false_positives / len(all_labels)

print(f"Test loss: {total_loss / len(test_loader):.4f}")
print(f"Accuracy (all normal): {accuracy:.4f}")
print(f"False Positive Rate: {false_positive_rate:.4f}")
print("Prediction distribution:", np.bincount(all_preds))
print('='*50)
print(classification_report(all_labels,all_preds))

Test loss: 1.5998
Accuracy (all normal): 0.3414
False Positive Rate: 0.3414
Prediction distribution: [6586 3414]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.34      0.51     10000

    accuracy                           0.34     10000
   macro avg       0.50      0.17      0.25     10000
weighted avg       1.00      0.34      0.51     10000



C:\Users\hana\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\hana\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\hana\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731:

In [77]:
user_control=pd.read_csv('second_dataset.csv')
user_control=user_control.sample(frac=1,random_state=42)
user_control_to_test=user_control[:10000]

C:\Users\hana\AppData\Local\Temp\ipykernel_34820\2627521233.py:1: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  user_control=pd.read_csv('second_dataset.csv')


In [78]:
user_control_to_test['label']= np.abs(user_control_to_test["label"]-1)

C:\Users\hana\AppData\Local\Temp\ipykernel_34820\2555362311.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_control_to_test['label']= np.abs(user_control_to_test["label"]-1)


In [79]:
dataset = Dataset.from_pandas(user_control_to_test)

def tokenize(batch):
    return tokenizer(
        batch['other_posts'],
        truncation=True,
        padding="max_length",
        max_length=512
    )

dataset = dataset.map(tokenize, batched=True)
dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

test_loader = DataLoader(dataset, batch_size=32, shuffle=False)


Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

In [80]:
from torch.nn.functional import softmax

total_loss = 0
all_preds = []
all_probs = []
all_labels = []

criterion = torch.nn.CrossEntropyLoss()

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        logits = outputs.logits
        loss = criterion(logits, labels)

        probs = softmax(logits, dim=1)
        preds = torch.argmax(probs, dim=1)

        total_loss += loss.item()

        all_preds.extend(preds.cpu().numpy())
        all_probs.extend(probs[:, 1].cpu().numpy())  # prob of mental illness
        all_labels.extend(labels.cpu().numpy())


In [81]:
from sklearn.metrics import classification_report
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

accuracy = (all_preds == all_labels).mean()

false_positives = (all_preds == 1).sum()
false_positive_rate = false_positives / len(all_labels)

print(f"Test loss: {total_loss / len(test_loader):.4f}")
print(f"Accuracy (all normal): {accuracy:.4f}")
print(f"False Positive Rate: {false_positive_rate:.4f}")
print("Prediction distribution:", np.bincount(all_preds))
print('='*50)
print(classification_report(all_labels,all_preds))

Test loss: 1.8329
Accuracy (all normal): 0.2480
False Positive Rate: 0.4899
Prediction distribution: [5101 4899]
              precision    recall  f1-score   support

           0       0.14      0.19      0.16      3891
           1       0.36      0.29      0.32      6109

    accuracy                           0.25     10000
   macro avg       0.25      0.24      0.24     10000
weighted avg       0.27      0.25      0.26     10000



In [ ]:
generated_data=pd.read_csv('test_data_5000.csv')


In [49]:
generated_data["label"] = (generated_data["group"] == "typical").astype(int)


In [51]:


dataset = Dataset.from_pandas(generated_data)

def tokenize(batch):
    return tokenizer(
        batch['response'],
        truncation=True,
        padding="max_length",
        max_length=512
    )

dataset = dataset.map(tokenize, batched=True)
dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

test_loader = DataLoader(dataset, batch_size=32, shuffle=False)



Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

In [52]:
from torch.nn.functional import softmax

total_loss = 0
all_preds = []
all_probs = []
all_labels = []

criterion = torch.nn.CrossEntropyLoss()

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        logits = outputs.logits
        loss = criterion(logits, labels)

        probs = softmax(logits, dim=1)
        preds = torch.argmax(probs, dim=1)

        total_loss += loss.item()

        all_preds.extend(preds.cpu().numpy())
        all_probs.extend(probs[:, 1].cpu().numpy())  # prob of mental illness
        all_labels.extend(labels.cpu().numpy())


In [53]:
from sklearn.metrics import classification_report
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

accuracy = (all_preds == all_labels).mean()

false_positives = (all_preds == 1).sum()
false_positive_rate = false_positives / len(all_labels)

print(f"Test loss: {total_loss / len(test_loader):.4f}")
print(f"Accuracy (all normal): {accuracy:.4f}")
print(f"False Positive Rate: {false_positive_rate:.4f}")
print("Prediction distribution:", np.bincount(all_preds))
print("="*50)
print(classification_report(all_labels, all_preds))

Test loss: 1.0245
Accuracy (all normal): 0.1052
False Positive Rate: 0.6134
Prediction distribution: [1933 3067]
              precision    recall  f1-score   support

           0       0.01      0.00      0.00      2563
           1       0.17      0.21      0.19      2437

    accuracy                           0.11      5000
   macro avg       0.09      0.11      0.10      5000
weighted avg       0.08      0.11      0.09      5000

